{
  "specName": "test-with-api-spec.js",
  "title": "An uncaught error was detected outside of a test",
  "suiteName": "",
  "testId": "r2",
  "testName": "An uncaught error was detected outside of a test",
  "testError": "The following error originated from your test code, not from Cypress.\n\n  > programmingWith is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nCheck your console for the stack trace or click this message to see where it originated from.",
  "testCommands": []
}
